<?php
/**
 * Font Icons
 *
 * @package    RB_Plugins
 * @subpackage RBELAD_Elementor_Addons
 */

namespace RBELAD_Elementor_Addons;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Icon Manager for font-icons.
 */
class Icons_Manager {
	/**
	 * Add RB Elementor icon set tab to Elementor Icons Manager.
	 *
	 * Filters the additional icon tabs and registers the RB Elementor icons.
	 *
	 * @param array $tabs Existing Elementor icon tabs.
	 * @return array Modified icon tabs including RB Elementor icons.
	 */
	public static function add_rbelad_icons_tab( $tabs ) {
		$tabs['rbelad-gf'] = array(
			'name'          => 'rbelad-gf',
			'label'         => esc_html__( 'RB General Icons', 'rb-addons-for-elementor' ),
			'url'           => RBELAD_CSS . 'rbelad-general-icons.css',
			'enqueue'       => array( RBELAD_CSS . 'rbelad-general-icons.css' ),
			'prefix'        => 'rbelad-gf-',
			'displayPrefix' => 'rbelad-gf-icon',
			'labelIcon'     => 'rbelad-gf-icon rbelad-gf-rb-addons',
			'ver'           => RBELAD_DEV_VERSION,
			'fetchJson'     => RBELAD_JS . 'rbelad-general-icons.js',
			'native'        => false,
		);
		return $tabs;
	}

	/**
	 * Get a list of rbelad icons
	 *
	 * @return array
	 */
	public static function get_rbelad_icons() {
		return array(
			'rbelad-gf-icon rbelad-gf-alerm-clock'       => 'alerm-clock',
			'rbelad-gf-icon rbelad-gf-alerm-clock-2'     => 'alerm-clock-2',
			'rbelad-gf-icon rbelad-gf-animated-text'     => 'animated-text',
			'rbelad-gf-icon rbelad-gf-apple'             => 'apple',
			'rbelad-gf-icon rbelad-gf-arrow-down-1'      => 'arrow-down-1',
			'rbelad-gf-icon rbelad-gf-arrow-right-1'     => 'arrow-right-1',
			'rbelad-gf-icon rbelad-gf-arrow-right-2'     => 'arrow-right-2',
			'rbelad-gf-icon rbelad-gf-arrow-right-3'     => 'arrow-right-3',
			'rbelad-gf-icon rbelad-gf-arrow-right-4'     => 'arrow-right-4',
			'rbelad-gf-icon rbelad-gf-arrow-right-5'     => 'arrow-right-5',
			'rbelad-gf-icon rbelad-gf-art-box'           => 'art-box',
			'rbelad-gf-icon rbelad-gf-audio'             => 'audio',
			'rbelad-gf-icon rbelad-gf-badge-top'         => 'badge-top',
			'rbelad-gf-icon rbelad-gf-badge-top-2'       => 'badge-top-2',
			'rbelad-gf-icon rbelad-gf-bed'               => 'bed',
			'rbelad-gf-icon rbelad-gf-behance'           => 'behance',
			'rbelad-gf-icon rbelad-gf-bill-recept'       => 'bill-recept',
			'rbelad-gf-icon rbelad-gf-bluetooth'         => 'bluetooth',
			'rbelad-gf-icon rbelad-gf-bookmark'          => 'bookmark',
			'rbelad-gf-icon rbelad-gf-box-open-1'        => 'box-open-1',
			'rbelad-gf-icon rbelad-gf-box-open-2'        => 'box-open-2',
			'rbelad-gf-icon rbelad-gf-brain-1'           => 'brain-1',
			'rbelad-gf-icon rbelad-gf-brain-2'           => 'brain-2',
			'rbelad-gf-icon rbelad-gf-brain-3'           => 'brain-3',
			'rbelad-gf-icon rbelad-gf-breadcrumbs'       => 'breadcrumbs',
			'rbelad-gf-icon rbelad-gf-brifecase-1'       => 'brifecase-1',
			'rbelad-gf-icon rbelad-gf-brifecase-2'       => 'brifecase-2',
			'rbelad-gf-icon rbelad-gf-builder-1'         => 'builder-1',
			'rbelad-gf-icon rbelad-gf-builder-2'         => 'builder-2',
			'rbelad-gf-icon rbelad-gf-builder-3'         => 'builder-3',
			'rbelad-gf-icon rbelad-gf-builder-4'         => 'builder-4',
			'rbelad-gf-icon rbelad-gf-builder-5'         => 'builder-5',
			'rbelad-gf-icon rbelad-gf-builder-6'         => 'builder-6',
			'rbelad-gf-icon rbelad-gf-bulb-1'            => 'bulb-1',
			'rbelad-gf-icon rbelad-gf-bulb-2'            => 'bulb-2',
			'rbelad-gf-icon rbelad-gf-bulb-3'            => 'bulb-3',
			'rbelad-gf-icon rbelad-gf-bulb-4'            => 'bulb-4',
			'rbelad-gf-icon rbelad-gf-business-hour'     => 'business-hour',
			'rbelad-gf-icon rbelad-gf-button'            => 'button',
			'rbelad-gf-icon rbelad-gf-button-group'      => 'button-group',
			'rbelad-gf-icon rbelad-gf-calendar'          => 'calendar',
			'rbelad-gf-icon rbelad-gf-camera'            => 'camera',
			'rbelad-gf-icon rbelad-gf-cart-1'            => 'cart-1',
			'rbelad-gf-icon rbelad-gf-cart-2'            => 'cart-2',
			'rbelad-gf-icon rbelad-gf-check-mark'        => 'check-mark',
			'rbelad-gf-icon rbelad-gf-chef'              => 'chef',
			'rbelad-gf-icon rbelad-gf-circle'            => 'circle',
			'rbelad-gf-icon rbelad-gf-clock-1'           => 'clock-1',
			'rbelad-gf-icon rbelad-gf-clock-2'           => 'clock-2',
			'rbelad-gf-icon rbelad-gf-cloud'             => 'cloud',
			'rbelad-gf-icon rbelad-gf-code'              => 'code',
			'rbelad-gf-icon rbelad-gf-codepen'           => 'codepen',
			'rbelad-gf-icon rbelad-gf-color-plate'       => 'color-plate',
			'rbelad-gf-icon rbelad-gf-comment'           => 'comment',
			'rbelad-gf-icon rbelad-gf-comment-2'         => 'comment-2',
			'rbelad-gf-icon rbelad-gf-comments'          => 'comments',
			'rbelad-gf-icon rbelad-gf-contact-form-7'    => 'contact-form-7',
			'rbelad-gf-icon rbelad-gf-content-box'       => 'content-box',
			'rbelad-gf-icon rbelad-gf-credit-card-1'     => 'credit-card-1',
			'rbelad-gf-icon rbelad-gf-credit-card-2'     => 'credit-card-2',
			'rbelad-gf-icon rbelad-gf-date-edit'         => 'date-edit',
			'rbelad-gf-icon rbelad-gf-divider'           => 'divider',
			'rbelad-gf-icon rbelad-gf-dollar-1'          => 'dollar-1',
			'rbelad-gf-icon rbelad-gf-dollar-2'          => 'dollar-2',
			'rbelad-gf-icon rbelad-gf-dongle'            => 'dongle',
			'rbelad-gf-icon rbelad-gf-dots-1'            => 'dots-1',
			'rbelad-gf-icon rbelad-gf-dots-2'            => 'dots-2',
			'rbelad-gf-icon rbelad-gf-download'          => 'download',
			'rbelad-gf-icon rbelad-gf-dribbble'          => 'dribbble',
			'rbelad-gf-icon rbelad-gf-email-1'           => 'email-1',
			'rbelad-gf-icon rbelad-gf-email-2'           => 'email-2',
			'rbelad-gf-icon rbelad-gf-email-3'           => 'email-3',
			'rbelad-gf-icon rbelad-gf-email-4'           => 'email-4',
			'rbelad-gf-icon rbelad-gf-email-5'           => 'email-5',
			'rbelad-gf-icon rbelad-gf-eye-1'             => 'eye-1',
			'rbelad-gf-icon rbelad-gf-eye-2'             => 'eye-2',
			'rbelad-gf-icon rbelad-gf-facebook-1'        => 'facebook-1',
			'rbelad-gf-icon rbelad-gf-facebook-2'        => 'facebook-2',
			'rbelad-gf-icon rbelad-gf-factory'           => 'factory',
			'rbelad-gf-icon rbelad-gf-faq'               => 'faq',
			'rbelad-gf-icon rbelad-gf-flag'              => 'flag',
			'rbelad-gf-icon rbelad-gf-flim'              => 'flim',
			'rbelad-gf-icon rbelad-gf-flip-box'          => 'flip-box',
			'rbelad-gf-icon rbelad-gf-flower-1'          => 'flower-1',
			'rbelad-gf-icon rbelad-gf-flower-2'          => 'flower-2',
			'rbelad-gf-icon rbelad-gf-flyer'             => 'flyer',
			'rbelad-gf-icon rbelad-gf-folder'            => 'folder',
			'rbelad-gf-icon rbelad-gf-github'            => 'github',
			'rbelad-gf-icon rbelad-gf-give-box'          => 'give-box',
			'rbelad-gf-icon rbelad-gf-graduate'          => 'graduate',
			'rbelad-gf-icon rbelad-gf-graduate-hat'      => 'graduate-hat',
			'rbelad-gf-icon rbelad-gf-graduate-hat-2'    => 'graduate-hat-2',
			'rbelad-gf-icon rbelad-gf-graduate-hat-3'    => 'graduate-hat-3',
			'rbelad-gf-icon rbelad-gf-growth-1'          => 'growth-1',
			'rbelad-gf-icon rbelad-gf-growth-2'          => 'growth-2',
			'rbelad-gf-icon rbelad-gf-growth-3'          => 'growth-3',
			'rbelad-gf-icon rbelad-gf-growth-4'          => 'growth-4',
			'rbelad-gf-icon rbelad-gf-hand-shape'        => 'hand-shape',
			'rbelad-gf-icon rbelad-gf-heading'           => 'heading',
			'rbelad-gf-icon rbelad-gf-helpline'          => 'helpline',
			'rbelad-gf-icon rbelad-gf-home-1'            => 'home-1',
			'rbelad-gf-icon rbelad-gf-home-2'            => 'home-2',
			'rbelad-gf-icon rbelad-gf-house-sale'        => 'house-sale',
			'rbelad-gf-icon rbelad-gf-html'              => 'html',
			'rbelad-gf-icon rbelad-gf-image'             => 'image',
			'rbelad-gf-icon rbelad-gf-image-2'           => 'image-2',
			'rbelad-gf-icon rbelad-gf-image-carousel'    => 'image-carousel',
			'rbelad-gf-icon rbelad-gf-image-carousel-2'  => 'image-carousel-2',
			'rbelad-gf-icon rbelad-gf-image-gallery'     => 'image-gallery',
			'rbelad-gf-icon rbelad-gf-instagram'         => 'instagram',
			'rbelad-gf-icon rbelad-gf-laboratory'        => 'laboratory',
			'rbelad-gf-icon rbelad-gf-leaf'              => 'leaf',
			'rbelad-gf-icon rbelad-gf-like'              => 'like',
			'rbelad-gf-icon rbelad-gf-link-broken'       => 'link-broken',
			'rbelad-gf-icon rbelad-gf-linkedin'          => 'linkedin',
			'rbelad-gf-icon rbelad-gf-linkedin-2'        => 'linkedin-2',
			'rbelad-gf-icon rbelad-gf-list'              => 'list',
			'rbelad-gf-icon rbelad-gf-list-2'            => 'list-2',
			'rbelad-gf-icon rbelad-gf-location-1'        => 'location-1',
			'rbelad-gf-icon rbelad-gf-location-2'        => 'location-2',
			'rbelad-gf-icon rbelad-gf-location-3'        => 'location-3',
			'rbelad-gf-icon rbelad-gf-location-4'        => 'location-4',
			'rbelad-gf-icon rbelad-gf-location-5'        => 'location-5',
			'rbelad-gf-icon rbelad-gf-location-6'        => 'location-6',
			'rbelad-gf-icon rbelad-gf-location-7'        => 'location-7',
			'rbelad-gf-icon rbelad-gf-location-8'        => 'location-8',
			'rbelad-gf-icon rbelad-gf-location-9'        => 'location-9',
			'rbelad-gf-icon rbelad-gf-logo'              => 'logo',
			'rbelad-gf-icon rbelad-gf-logo-carousel'     => 'logo-carousel',
			'rbelad-gf-icon rbelad-gf-lottie'            => 'lottie',
			'rbelad-gf-icon rbelad-gf-love-1'            => 'love-1',
			'rbelad-gf-icon rbelad-gf-love-2'            => 'love-2',
			'rbelad-gf-icon rbelad-gf-low-1'             => 'low-1',
			'rbelad-gf-icon rbelad-gf-mailchimp'         => 'mailchimp',
			'rbelad-gf-icon rbelad-gf-man-1'             => 'man-1',
			'rbelad-gf-icon rbelad-gf-measurement-tape'  => 'measurement-tape',
			'rbelad-gf-icon rbelad-gf-menu'              => 'menu',
			'rbelad-gf-icon rbelad-gf-mike-1'            => 'mike-1',
			'rbelad-gf-icon rbelad-gf-mike-2'            => 'mike-2',
			'rbelad-gf-icon rbelad-gf-movie-camera'      => 'movie-camera',
			'rbelad-gf-icon rbelad-gf-navigation'        => 'navigation',
			'rbelad-gf-icon rbelad-gf-next'              => 'next',
			'rbelad-gf-icon rbelad-gf-notebook-1'        => 'notebook-1',
			'rbelad-gf-icon rbelad-gf-notebook-2'        => 'notebook-2',
			'rbelad-gf-icon rbelad-gf-notification'      => 'notification',
			'rbelad-gf-icon rbelad-gf-page-title'        => 'page-title',
			'rbelad-gf-icon rbelad-gf-paint-pen'         => 'paint-pen',
			'rbelad-gf-icon rbelad-gf-path-1'            => 'path-1',
			'rbelad-gf-icon rbelad-gf-pdf'               => 'pdf',
			'rbelad-gf-icon rbelad-gf-pencil-1'          => 'pencil-1',
			'rbelad-gf-icon rbelad-gf-pencil-box'        => 'pencil-box',
			'rbelad-gf-icon rbelad-gf-phone-1'           => 'phone-1',
			'rbelad-gf-icon rbelad-gf-phone-2'           => 'phone-2',
			'rbelad-gf-icon rbelad-gf-phone-3'           => 'phone-3',
			'rbelad-gf-icon rbelad-gf-phone-4'           => 'phone-4',
			'rbelad-gf-icon rbelad-gf-phone-5'           => 'phone-5',
			'rbelad-gf-icon rbelad-gf-phone-6'           => 'phone-6',
			'rbelad-gf-icon rbelad-gf-pinterest'         => 'pinterest',
			'rbelad-gf-icon rbelad-gf-play'              => 'play',
			'rbelad-gf-icon rbelad-gf-portfolio'         => 'portfolio',
			'rbelad-gf-icon rbelad-gf-post-carousel'     => 'post-carousel',
			'rbelad-gf-icon rbelad-gf-post-edit'         => 'post-edit',
			'rbelad-gf-icon rbelad-gf-post-excerpt'      => 'post-excerpt',
			'rbelad-gf-icon rbelad-gf-post-grid'         => 'post-grid',
			'rbelad-gf-icon rbelad-gf-post-grid-2'       => 'post-grid-2',
			'rbelad-gf-icon rbelad-gf-post-title'        => 'post-title',
			'rbelad-gf-icon rbelad-gf-price'             => 'price',
			'rbelad-gf-icon rbelad-gf-profile-card'      => 'profile-card',
			'rbelad-gf-icon rbelad-gf-profile-card-2'    => 'profile-card-2',
			'rbelad-gf-icon rbelad-gf-progress'          => 'progress',
			'rbelad-gf-icon rbelad-gf-protect'           => 'protect',
			'rbelad-gf-icon rbelad-gf-quote-left'        => 'quote-left',
			'rbelad-gf-icon rbelad-gf-quote-left-2'      => 'quote-left-2',
			'rbelad-gf-icon rbelad-gf-quote-left-3'      => 'quote-left-3',
			'rbelad-gf-icon rbelad-gf-quote-left-4'      => 'quote-left-4',
			'rbelad-gf-icon rbelad-gf-quote-right'       => 'quote-right',
			'rbelad-gf-icon rbelad-gf-quote-right-2'     => 'quote-right-2',
			'rbelad-gf-icon rbelad-gf-quote-right-3'     => 'quote-right-3',
			'rbelad-gf-icon rbelad-gf-quote-right-4'     => 'quote-right-4',
			'rbelad-gf-icon rbelad-gf-rating'            => 'rating',
			'rbelad-gf-icon rbelad-gf-rb-addons'         => 'rb-addons',
			'rbelad-gf-icon rbelad-gf-read-more'         => 'read-more',
			'rbelad-gf-icon rbelad-gf-restaurant'        => 'restaurant',
			'rbelad-gf-icon rbelad-gf-ribbon-arrow-1'    => 'ribbon-arrow-1',
			'rbelad-gf-icon rbelad-gf-rocket-1'          => 'rocket-1',
			'rbelad-gf-icon rbelad-gf-save'              => 'save',
			'rbelad-gf-icon rbelad-gf-scroll-down'       => 'scroll-down',
			'rbelad-gf-icon rbelad-gf-search-1'          => 'search-1',
			'rbelad-gf-icon rbelad-gf-search-2'          => 'search-2',
			'rbelad-gf-icon rbelad-gf-search-3'          => 'search-3',
			'rbelad-gf-icon rbelad-gf-search-4'          => 'search-4',
			'rbelad-gf-icon rbelad-gf-section-header'    => 'section-header',
			'rbelad-gf-icon rbelad-gf-setting-1'         => 'setting-1',
			'rbelad-gf-icon rbelad-gf-setting-2'         => 'setting-2',
			'rbelad-gf-icon rbelad-gf-setting-3'         => 'setting-3',
			'rbelad-gf-icon rbelad-gf-share-share-1'     => 'share-share-1',
			'rbelad-gf-icon rbelad-gf-share-share-2'     => 'share-share-2',
			'rbelad-gf-icon rbelad-gf-shower'            => 'shower',
			'rbelad-gf-icon rbelad-gf-site-logo'         => 'site-logo',
			'rbelad-gf-icon rbelad-gf-site-title'        => 'site-title',
			'rbelad-gf-icon rbelad-gf-slider'            => 'slider',
			'rbelad-gf-icon rbelad-gf-social-icons'      => 'social-icons',
			'rbelad-gf-icon rbelad-gf-spacer'            => 'spacer',
			'rbelad-gf-icon rbelad-gf-star'              => 'star',
			'rbelad-gf-icon rbelad-gf-star-2'            => 'star-2',
			'rbelad-gf-icon rbelad-gf-star-3'            => 'star-3',
			'rbelad-gf-icon rbelad-gf-star-4'            => 'star-4',
			'rbelad-gf-icon rbelad-gf-statue-of-liberty' => 'statue-of-liberty',
			'rbelad-gf-icon rbelad-gf-step-flew-1'       => 'step-flew-1',
			'rbelad-gf-icon rbelad-gf-step-flew-2'       => 'step-flew-2',
			'rbelad-gf-icon rbelad-gf-step-flew-3'       => 'step-flew-3',
			'rbelad-gf-icon rbelad-gf-tabs'              => 'tabs',
			'rbelad-gf-icon rbelad-gf-tag'               => 'tag',
			'rbelad-gf-icon rbelad-gf-tag-2'             => 'tag-2',
			'rbelad-gf-icon rbelad-gf-target'            => 'target',
			'rbelad-gf-icon rbelad-gf-team-1'            => 'team-1',
			'rbelad-gf-icon rbelad-gf-team-2'            => 'team-2',
			'rbelad-gf-icon rbelad-gf-testimonial'       => 'testimonial',
			'rbelad-gf-icon rbelad-gf-testimonial-carousel' => 'testimonial-carousel',
			'rbelad-gf-icon rbelad-gf-text-editor'       => 'text-editor',
			'rbelad-gf-icon rbelad-gf-text-path'         => 'text-path',
			'rbelad-gf-icon rbelad-gf-tiktok'            => 'tiktok',
			'rbelad-gf-icon rbelad-gf-toggle'            => 'toggle',
			'rbelad-gf-icon rbelad-gf-tree'              => 'tree',
			'rbelad-gf-icon rbelad-gf-triangle'          => 'triangle',
			'rbelad-gf-icon rbelad-gf-trophy'            => 'trophy',
			'rbelad-gf-icon rbelad-gf-twitter'           => 'twitter',
			'rbelad-gf-icon rbelad-gf-twitter-x'         => 'twitter-x',
			'rbelad-gf-icon rbelad-gf-underline-1'       => 'underline-1',
			'rbelad-gf-icon rbelad-gf-underline-2'       => 'underline-2',
			'rbelad-gf-icon rbelad-gf-underline-3'       => 'underline-3',
			'rbelad-gf-icon rbelad-gf-underline-4'       => 'underline-4',
			'rbelad-gf-icon rbelad-gf-usb'               => 'usb',
			'rbelad-gf-icon rbelad-gf-user-1'            => 'user-1',
			'rbelad-gf-icon rbelad-gf-user-2'            => 'user-2',
			'rbelad-gf-icon rbelad-gf-varification'      => 'varification',
			'rbelad-gf-icon rbelad-gf-web'               => 'web',
			'rbelad-gf-icon rbelad-gf-web-2'             => 'web-2',
			'rbelad-gf-icon rbelad-gf-web-3'             => 'web-3',
			'rbelad-gf-icon rbelad-gf-web-4'             => 'web-4',
			'rbelad-gf-icon rbelad-gf-web-header'        => 'web-header',
			'rbelad-gf-icon rbelad-gf-whatsapp'          => 'whatsapp',
			'rbelad-gf-icon rbelad-gf-windows-10'        => 'windows-10',
			'rbelad-gf-icon rbelad-gf-yoga-1'            => 'yoga-1',
			'rbelad-gf-icon rbelad-gf-yoga-2'            => 'yoga-2',
			'rbelad-gf-icon rbelad-gf-yoga-3'            => 'yoga-3',
			'rbelad-gf-icon rbelad-gf-youtube'           => 'youtube',
		);
	}
}
